reload "user.plugins"
reload "user.options"
reload "user.keymaps"
reload "user.lsp"
reload "user.whichkey"
reload "user.telescope"
reload "user.autopairs"
-- reload "user.cmp"
reload "user.indent-blankline"
reload "user.leap"
reload "user.lualine"
reload "user.nvim-tree"
